apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekslearning
  labels:
    app: ekslearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ekslearning
  template:
    metadata:
      labels:
        app: ekslearning
    spec:
      containers:
        - name: ekslearning
          image: 703997246287.dkr.ecr.us-east-2.amazonaws.com/ekslearning01:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080